name: Website Monitor

on:
  schedule:
    # Run 3 times a day at even intervals (every 8 hours)
    - cron: '0 0,8,16 * * *'  # 00:00, 08:00, 16:00 UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Allow workflow to push changes

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run website monitor
      env:
        WEBSITES_TO_MONITOR: ${{ secrets.WEBSITES_TO_MONITOR }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python monitor.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add website_hashes.json
        git diff --staged --quiet || git commit -m "Update website hashes [skip ci]"
        git push
